### PR TITLE
Update Dependencies

### PR DESCRIPTION
**Pull request by Serubin**
## Description
Update dependencies to latest version - general clean up of deps.

Includes some duplicate work from #151 - may require a simple rebase once one or the other gets merged.

### CODE REVIEW

**Comment by Serubin** [comment]
@mohsintahir @MapleSimon What's the process for getting a review?

**Comment by mohsintahir** [comment]
@Serubin I think you can create a PR and assign it to me as reviewer if you want a review.

**Comment by Serubin** [comment]
@mohsintahir I can't do anything but submit PRs/Issues. Maple removed my access

**Comment by mohsintahir** [comment]
@Serubin Can you kindly mention me in comment to review something if you want to ?

**Comment by Serubin** [comment]
@mohsintahir Already done in all three PRs.

**Comment by mohsintahir** [comment]
@Serubin  why have we removed core-js from dependencies?

**Comment by Serubin** [comment]
It's not used and we have no need for these types of polyfills

**Pull request merged**
